name: CI

on:
  workflow_dispatch:

jobs:
  sign:
    runs-on: macos-11
    timeout-minutes: 30
    env:
      SECRET_URL: "${{ docker.pkg.github.com }}"
      SECRET_KEY: "${{ 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 }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v2.2.1
      - name: Sign
        run: |
          sudo xcode-select -s /Applications/Xcode_12.5.1.app
          ./sign.sh
